spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master: 
          username: sa
          password: ""
          url: jdbc:h2:mem:db1
          driver-class-name: org.h2.Driver
          schema: sql/schema-repo.sql
