server:
  port: 12345
spring:
  application:
    name: bpm-repo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active:
    - dev
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          username: sa
          password: ""
          url: jdbc:h2:mem:db1
          driver-class-name: org.h2.Driver
          schema: sql/schema-repo.sql

management:
  server:
    port: 9090
    servlet:
      context-path: /console
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - loggers
        - mappings
        - threaddump
logging:
  level:
    root: info
    sql: info
    web: info

mybatis-plus:
  mapper-locations:
  - classpath*:mybatis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
